server:
  port: 8084

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql:///testone
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.czk: debug

